### ISSUE TITLE
no funtionality in 2024

### ISSUE THREAD

**Issue by Siletrea** [OvertAnglerfish/Plushie-Tycoon#1]
I'm used to older scripts having a few issues nowadays but a simple "replace all" command with "http" to "https" usually fixes 99.9% of everything! in this case however I've attempted to get this one going several times and it just never starts, I start the new game, I go to the main page, I set the timezone to +11 so I can play in the evenings, I wait! and nothing happens, no indications of anything trying to happen either. 

the "set up new store" button does not exist as far as I can find one. Unless its a translation error and I'm meant to go to the store tab and make a rental payment? I don't think that's the case. also you say the time can be changed in the script but I couldn't find the area to change it.

would you kindly update this script? I'd love to get this going! I have a terrible time getting the materials to make blue and yellow ogrins at a cheap enough price to pull a profit reliably

**Comment by PhilShih** [comment]
Hey @Siletrea, appreciate you reaching out and trying this script. This was a small personal project I worked on nearly a decade ago and I'm no longer have the time or interest to update this. If it's broken, it's broken, unfortunately.

**Comment by Siletrea** [comment]
> Hey @Siletrea, appreciate you reaching out and trying this script. This was a small personal project I worked on nearly a decade ago and I'm no longer have the time or interest to update this. If it's broken, it's broken, unfortunately.

I see! that's unfortunate, while also understandable! thank you for getting back to me and I wish you the best on future projects!
